#!/usr/bin/env python3
"""Regenerate p4_dashboard_html.h from assets/dashboard.html (gzip).

Injects username + SHA-256(username:password) from secrets.yaml so dashboard
Login works on plain HTTP without ESPHome Basic Auth (which would block guest
SSE /events reads). Password itself is never written into the HTML.
"""
from __future__ import annotations

import gzip
import hashlib
import pathlib
import re
import sys
import time

ROOT = pathlib.Path(__file__).resolve().parents[1]
SRC = ROOT / "assets" / "dashboard.html"
OUT = ROOT / "p4_dashboard_html.h"
SECRETS = ROOT / "secrets.yaml"
TOKEN_PLACEHOLDER = "__DASHBOARD_AUTH_TOKEN__"
USER_PLACEHOLDER = "__DASHBOARD_AUTH_USER__"
BUILD_PLACEHOLDER = "__DASHBOARD_BUILD_ID__"


def _secret(name: str) -> str:
    text = SECRETS.read_text(encoding="utf-8")
    m = re.search(rf"^{re.escape(name)}\s*:\s*(.+)$", text, re.MULTILINE)
    if not m:
        raise SystemExit(f"Missing {name} in secrets.yaml")
    val = m.group(1).strip()
    if (val.startswith('"') and val.endswith('"')) or (val.startswith("'") and val.endswith("'")):
        val = val[1:-1]
    return val


def main() -> int:
    user = _secret("web_server_username")
    password = _secret("web_server_password")
    token = hashlib.sha256(f"{user}:{password}".encode("utf-8")).hexdigest()
    build_id = time.strftime("%Y%m%d-%H%M")

    raw_text = SRC.read_text(encoding="utf-8")
    for ph in (TOKEN_PLACEHOLDER, USER_PLACEHOLDER, BUILD_PLACEHOLDER):
        if ph not in raw_text:
            raise SystemExit(f"assets/dashboard.html missing placeholder {ph!r}")

    # Escape username for JS single-quoted string
    user_js = user.replace("\\", "\\\\").replace("'", "\\'")
    raw_text = (
        raw_text.replace(TOKEN_PLACEHOLDER, token)
        .replace(USER_PLACEHOLDER, user_js)
        .replace(BUILD_PLACEHOLDER, build_id)
    )
    raw = raw_text.encode("utf-8")

    gz = gzip.compress(raw, compresslevel=9)
    lines = [
        "#pragma once",
        "// Auto-generated by scripts/embed_dashboard.py — do not edit by hand.",
        f"// Source: assets/dashboard.html ({len(raw)} bytes) -> gzip ({len(gz)} bytes)",
        f"// Auth: user={user!r} token=SHA-256(user:pass) build={build_id}",
        "#include <cstddef>",
        "#include <cstdint>",
        "static const uint8_t P4_DASHBOARD_HTML_GZ[] = {",
    ]
    for i in range(0, len(gz), 16):
        chunk = ", ".join(f"0x{b:02x}" for b in gz[i : i + 16])
        lines.append(f"  {chunk},")
    lines.append("};")
    lines.append(f"static const size_t P4_DASHBOARD_HTML_GZ_LEN = {len(gz)};")
    OUT.write_text("\n".join(lines) + "\n")
    print(f"Wrote {OUT.relative_to(ROOT)} ({len(gz)} gzipped bytes from {len(raw)} raw)")
    print(f"Injected auth user={user!r} build={build_id} (password hash only)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
