#!/usr/bin/env python3
"""Regenerate p4_dashboard_html.h from assets/dashboard.html (gzip).

Injects a SHA-256 of web_server_username:web_server_password from secrets.yaml
so dashboard Login can verify the device credential without ESPHome HTTP Basic
Auth (which would also block guest GET /api/states).
"""
from __future__ import annotations

import gzip
import hashlib
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
SRC = ROOT / "assets" / "dashboard.html"
OUT = ROOT / "p4_dashboard_html.h"
SECRETS = ROOT / "secrets.yaml"
AUTH_PLACEHOLDER = "__DASHBOARD_AUTH_TOKEN__"


def _secret(name: str) -> str:
    text = SECRETS.read_text(encoding="utf-8")
    # Match: name: value  or  name: "value"  (no nested quotes)
    m = re.search(rf"^{re.escape(name)}\s*:\s*(.+)$", text, re.MULTILINE)
    if not m:
        raise SystemExit(f"Missing {name} in secrets.yaml")
    val = m.group(1).strip()
    if (val.startswith('"') and val.endswith('"')) or (val.startswith("'") and val.endswith("'")):
        val = val[1:-1]
    return val


def main() -> int:
    user = _secret("web_server_username")
    password = _secret("web_server_password")
    token = hashlib.sha256(f"{user}:{password}".encode("utf-8")).hexdigest()

    raw_text = SRC.read_text(encoding="utf-8")
    if AUTH_PLACEHOLDER not in raw_text:
        raise SystemExit(
            f"assets/dashboard.html must contain placeholder {AUTH_PLACEHOLDER!r} "
            "(login hash injection point)"
        )
    raw_text = raw_text.replace(AUTH_PLACEHOLDER, token)
    raw = raw_text.encode("utf-8")

    gz = gzip.compress(raw, compresslevel=9)
    lines = [
        "#pragma once",
        "// Auto-generated by scripts/embed_dashboard.py — do not edit by hand.",
        f"// Source: assets/dashboard.html ({len(raw)} bytes) -> gzip ({len(gz)} bytes)",
        "// Auth token: SHA-256(web_server_username:web_server_password) from secrets.yaml",
        "#include <cstddef>",
        "#include <cstdint>",
        "static const uint8_t P4_DASHBOARD_HTML_GZ[] = {",
    ]
    for i in range(0, len(gz), 16):
        chunk = ", ".join(f"0x{b:02x}" for b in gz[i : i + 16])
        lines.append(f"  {chunk},")
    lines.append("};")
    lines.append(f"static const size_t P4_DASHBOARD_HTML_GZ_LEN = {len(gz)};")
    OUT.write_text("\n".join(lines) + "\n")
    print(f"Wrote {OUT.relative_to(ROOT)} ({len(gz)} gzipped bytes from {len(raw)} raw)")
    print("Injected dashboard auth token from secrets.yaml (hash only; password not printed)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
